from enum import Enum


class ErrorCode(str, Enum):
    # System Errors (10xx)
    INTERNAL_SERVER_ERROR = "ERR_1000_INTERNAL_SERVER_ERROR"
    DATABASE_ERROR = "ERR_1001_DATABASE_ERROR"
    REDIS_CACHE_ERROR = "ERR_1002_REDIS_CACHE_ERROR"
    VALIDATION_ERROR = "ERR_1003_VALIDATION_ERROR"
    SLA_TIMEOUT_EXCEEDED = "ERR_1004_SLA_TIMEOUT_EXCEEDED"

    # Multi-Tenant Errors (20xx)
    TENANT_MISSING_HEADER = "ERR_2000_TENANT_MISSING_HEADER"
    TENANT_NOT_FOUND = "ERR_2001_TENANT_NOT_FOUND"
    TENANT_INACTIVE = "ERR_2002_TENANT_INACTIVE"
    RATE_LIMIT_EXCEEDED = "ERR_2003_RATE_LIMIT_EXCEEDED"

    # Authentication & Security (30xx)
    UNAUTHORIZED = "ERR_3000_UNAUTHORIZED"
    INVALID_TOKEN = "ERR_3001_INVALID_TOKEN"
    EXPIRED_TOKEN = "ERR_3002_EXPIRED_TOKEN"
    INSUFFICIENT_PERMISSIONS = "ERR_3003_INSUFFICIENT_PERMISSIONS"

    # Rule Engine Errors (40xx)
    RULE_EVALUATION_FAILED = "ERR_4000_RULE_EVALUATION_FAILED"
    JDM_NOT_FOUND = "ERR_4001_JDM_NOT_FOUND"
    INVALID_JDM_SYNTAX = "ERR_4002_INVALID_JDM_SYNTAX"
    BANK_POLICY_MISSING = "ERR_4003_BANK_POLICY_MISSING"

    # Resource Errors (50xx)
    APPLICATION_NOT_FOUND = "ERR_5000_APPLICATION_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "ERR_5001_RESOURCE_ALREADY_EXISTS"
