# Latency SLA Targets (in milliseconds)
SLA_TARGET_SIMPLE_GET_MS: float = 30.0
SLA_TARGET_CRUD_EVAL_MS: float = 80.0
SLA_TARGET_ZEN_RAM_MS: float = 10.0
SLA_TARGET_TOTAL_END_TO_END_MS: float = 100.0

# Database Connection Pool Tuning
DB_POOL_SIZE: int = 20
DB_MAX_OVERFLOW: int = 10
DB_POOL_RECYCLE_SECONDS: int = 3600
DB_POOL_PRE_PING: bool = True

# Business Rule Threshold Defaults
MIN_APPLICANT_AGE: int = 21
MAX_SALARIED_EMI_AGE: int = 60
MAX_SELF_EMPLOYED_EMI_AGE: int = 65
MIN_NRI_STAY_DAYS: int = 182
MIN_SALARIED_NET_MONTHLY_INCOME: float = 25000.0
MIN_SALARIED_TOTAL_WORK_EXP_YEARS: int = 1
MIN_SELF_EMPLOYED_BUSINESS_EXP_YEARS: int = 2
MIN_SELF_EMPLOYED_CURRENT_ITR: float = 300000.0
MIN_SELF_EMPLOYED_PREVIOUS_ITR: float = 100000.0
MIN_SELF_EMPLOYED_LOAN_AMOUNT: float = 100000.0
DPD_WRITE_OFF_MAX_TOLERANCE_DAYS: int = 90

# Rate Limiting Defaults
DEFAULT_TENANT_RATE_LIMIT_PER_MINUTE: int = 600

# Cache SWR & Expiry Limits (in seconds)
SWR_CACHE_MAX_AGE_SECONDS: int = 10
SWR_CACHE_STALE_WHILE_REVALIDATE_SECONDS: int = 60
